project:
  type: website
  output-dir: docs

theme:
  light: default
  dark: [default, theme-dark.scss]
  
website:
  page-navigation: true
  title: "Survive with Omics"
  repo-url: https://github.com/ocbe-uio/survomics
  repo-actions: [source, issue]
  
  navbar:
    background: light
    search: true
    collapse-below: sm
    left: 
      - href: survomics.html#introduction
        text: "Introduction"
      - href: survomics.html#tcga-survival-and-clinical-data
        text: "Clinical data"
      - href: survomics.html#tcga-omics-data
        text: "Omics data"
      - href: survomics.html#survival-analysis-with-low-dimensional-input-data
        text: "Low dimension"
      - href: survomics.html#survival-analysis-with-high-dimensional-input-data
        text: "High dimension"
      - href: survomics.html#survival-model-validation
        text: "Model validation"
      - href: survomics.html#multi-omics-integrative-modeling
        text: "Multi-omics"
        
    right: 
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ocbe-uio/survomics
          - text: Report a Bug
            url:  https://github.com/ocbe-uio/survomics/issues/new


format:
  html:
    theme: default
    toc: true
    toc-depth: 4
    appendix-style: none
    bibliography: "references.bib"
    fig-align: left
    
    lang: en
    language: 
      title-block-published: "UPDATED"
      
    page-layout: full
    grid: 
      sidebar-width: 350px
      margin-width: 350px
    
  # pdf:
  #   geometry:
  #     - bottom=17mm
  #     - left=15mm
  #     - right=15mm
  #   fontsize: 16pt
    