project:
  type: website
  output-dir: docs

theme:
  light: default
  dark: [default, theme-dark.scss]
  
website:
  page-navigation: true
  title: "Survive with Omics"
  repo-url: https://github.com/ocbe-uio/survomics
  repo-actions: [source, issue]
  
  search: 
    location: navbar
    type: overlay
  
  navbar:
    background: light
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/ocbe-uio/survomics
          - text: Report a Bug
            url:  https://github.com/ocbe-uio/survomics/issues/new


format:
  html:
    page-layout: full
    grid: 
      sidebar-width: 350px
      margin-width: 350px
    